export enum RouteParamEnum {
  idCharacter = 'idCharacter',
  idFileUpload = 'idFileUpload',
  idGame = 'idGame',
  idGameMode = 'idGameMode',
  idGameModeCharacter = 'idGameModeCharacter',
  idGameModePlatform = 'idGameModePlatform',
  idGameModeType = 'idGameModeType',
  idLike = 'idLike',
  idMode = 'idMode',
  idPlatform = 'idPlatform',
  idReference = 'idReference',
  idReport = 'idReport',
  idRole = 'idRole',
  idScore = 'idScore',
  idScorePlayer = 'idScorePlayer',
  idScorePlayerProof = 'idScorePlayerProof',
  idSite = 'idSite',
  idStage = 'idStage',
  idUser = 'idUser',
  idUserLink = 'idUserLink',
  idUserRole = 'idUserRole',
  idType = 'idType',

  token = 'token',
  username = 'username',
}
